### ISSUE TITLE
provision.sh not relativ path to docker-compose.yaml

### ISSUE THREAD

**Issue by FrauElster** [ibm-silvergate/netcomposer#25] opened 2018-12-10 12:07 UTC
If provision.sh is executed in netcomposer/out/samplenet/ instead of ./out/samplenet/provision.sh in netcomposer directory, it throws  ERROR: .FileNotFoundError: [Errno 2] No such file or directory: '././out/samplenet/docker-compose.yaml'. 
Path is not relative to script

**Comment by erNail** [comment] 2018-12-10 12:19
Duplicate of #9. Can be closed.

**Closed as completed** 2020-05-22 16:32 UTC
